### PR TITLE
Add code of conduct 

### PR DESCRIPTION
**Pull request by brucellino**
The standard contributor covenant is proposed as a code of conduct. Some contact details may need to be changed.

### CODE REVIEW

**Review by gwarf — CHANGES_REQUESTED** [review]
Thanks, if possible please separate the ansible updates from the code of conduct addition.
It may also be better to not output the secret_key in the debug log, thanks!

**Comment by brucellino** [comment]
Thanks for the review @gwarf 
I will address the requested changes in a subsequent commit.

**Comment by brucellino** [comment]
@gwarf I've made the changes. I think you can approve and merge.

**Comment by brucellino** [comment]
@gwarf Can we merge this now please ?

**Review by gwarf — APPROVED** [review]

**Pull request merged**
